// GENERATED by scripts/gen_types.py — do not edit by hand.
/* eslint-disable */

export interface AssistantDelta {
  run_id?: null | string;
  seq?: number;
  text: string;
}

export interface BudgetWarning {
  run_id?: null | string;
  seq?: number;
  budget: string;
  used: number;
  limit: number;
}

export type ConfigGetParams = Record<string, unknown>;

export interface ErrorNote {
  run_id?: null | string;
  seq?: number;
  code: string;
  message: string;
  hint?: null | string;
}

export interface EscalationNote {
  run_id?: null | string;
  seq?: number;
  task_id: string;
  rung: string;
  attempt?: number;
}

export interface ImageNote {
  run_id?: null | string;
  seq?: number;
  artifact_id: string;
  dims?: number[];
  region?: null | number[];
  caption?: null | string;
}

export interface MemoryListParams {
  kind?: null | string;
}

export interface MemoryReviewParams {
  memory_id: string;
  action: "approve" | "purge";
}

export interface ModelInfo {
  id: string;
  family?: null | string;
  engine: string;
  params_b?: number;
  capabilities?: string[];
  roles?: string[];
  status?: string;
  healthy?: boolean | null;
  vram_gb?: number;
  quant?: null | string;
  local?: boolean;
  path?: null | string;
  probes_passed?: null | number;
  probes_total?: null | number;
}

export interface ModelsAddParams {
  path: string;
  allow_large?: boolean;
}

export type ModelsListParams = Record<string, unknown>;

export interface ModelsListResult {
  models?: ModelInfo[];
}

export interface ModelsProbeParams {
  model_id: string;
}

export interface ModelsRemoveParams {
  model_id: string;
}

export interface PermissionRequest {
  run_id?: null | string;
  seq?: number;
  request_id: string;
  tool: string;
  args?: Record<string, unknown>;
  rule?: Record<string, unknown>;
  explanation?: null | string;
}

export type PingParams = Record<string, unknown>;

export interface PingResult {
  pong?: boolean;
  version?: string;
}

export interface PlanUpdated {
  run_id?: null | string;
  seq?: number;
  plan: Record<string, unknown>;
}

export interface QuestionNote {
  run_id?: null | string;
  seq?: number;
  request_id: string;
  questions: string[];
}

export interface RagSearchParams {
  query: string;
  collections?: string[];
  k?: number;
  mode?: "hybrid" | "lexical" | "dense" | "visual";
}

export interface RunApproveParams {
  run_id: string;
  request_id: string;
  decision: "once" | "always" | "deny";
  note?: null | string;
  answers?: null | string[];
}

export interface RunCancelParams {
  run_id: string;
}

export interface RunFinished {
  run_id?: null | string;
  seq?: number;
  response_kind?: "workflow" | "conversation";
  status?: string;
  summary?: string;
  artifacts?: Record<string, unknown>[];
  assumptions?: string[];
  unverified?: string[];
  budget_used?: Record<string, unknown>;
}

export interface RunPlanUpdateParams {
  run_id: string;
  plan: Record<string, unknown>;
}

export interface RunStats {
  run_id?: null | string;
  seq?: number;
  tokens_in?: number;
  tokens_out?: number;
  context_pct?: number;
  elapsed_s?: number;
  cost_saved_inr?: number;
  active_model?: string;
}

export interface SealEventNote {
  run_id?: null | string;
  seq?: number;
  kind: string;
  process?: string;
  dest?: string;
  port?: null | number;
  detail?: Record<string, unknown>;
}

export type SealStatusParams = Record<string, unknown>;

export interface SessionCreateParams {
  workspace: string;
  collections?: string[];
  mode?: "ask" | "auto" | "plan";
  title?: null | string;
}

export interface SessionCreateResult {
  session_id: string;
}

export interface SessionForkParams {
  session_id: string;
}

export interface SessionInfo {
  session_id: string;
  title?: null | string;
  workspace: string;
  mode: "ask" | "auto" | "plan";
  status: string;
  created_at: string;
  updated_at: string;
  last_goal?: null | string;
}

export interface SessionListParams {
  limit?: number;
}

export interface SessionListResult {
  sessions?: SessionInfo[];
}

export interface SessionPromptParams {
  session_id: string;
  text: string;
  attachments?: string[];
  mode?: "ask" | "auto" | "plan" | null;
  budget_overrides?: Record<string, number> | null;
}

export interface SessionPromptResult {
  run_id: string;
}

export interface SessionResumeParams {
  session_id: string;
  last_seq?: number;
}

export interface SkillsApproveParams {
  skill_id: string;
  action: "approve" | "reject";
}

export type SkillsListParams = Record<string, unknown>;

export interface TaskUpdated {
  run_id?: null | string;
  seq?: number;
  task: Record<string, unknown>;
}

export interface ThinkingDelta {
  run_id?: null | string;
  seq?: number;
  text: string;
}

export interface ToolFinished {
  run_id?: null | string;
  seq?: number;
  step_id: string;
  tool?: string;
  summary?: string;
  artifact_id?: null | string;
  ok?: boolean;
}

export interface ToolOutputDelta {
  run_id?: null | string;
  seq?: number;
  step_id: string;
  text: string;
}

export interface ToolStarted {
  run_id?: null | string;
  seq?: number;
  step_id: string;
  task_id?: null | string;
  tool: string;
  args?: Record<string, unknown>;
}

export interface TraceGetParams {
  run_id: string;
}

export interface VerifyResultNote {
  run_id?: null | string;
  seq?: number;
  task_id: string;
  report: Record<string, unknown>;
}

export interface RequestParamsMap { 'config.get': ConfigGetParams, 'memory.list': MemoryListParams, 'memory.review': MemoryReviewParams, 'models.add': ModelsAddParams, 'models.list': ModelsListParams, 'models.probe': ModelsProbeParams, 'models.remove': ModelsRemoveParams, 'ping': PingParams, 'rag.search': RagSearchParams, 'run.approve': RunApproveParams, 'run.cancel': RunCancelParams, 'run.plan.update': RunPlanUpdateParams, 'seal.demo': SealStatusParams, 'seal.status': SealStatusParams, 'seal.verify': SealStatusParams, 'session.create': SessionCreateParams, 'session.fork': SessionForkParams, 'session.list': SessionListParams, 'session.prompt': SessionPromptParams, 'session.resume': SessionResumeParams, 'skills.approve': SkillsApproveParams, 'skills.list': SkillsListParams, 'trace.get': TraceGetParams }

export interface RequestResultMap { 'models.list': ModelsListResult, 'ping': PingResult, 'session.create': SessionCreateResult, 'session.list': SessionListResult, 'session.prompt': SessionPromptResult }

export interface NotificationMap { 'assistant.delta': AssistantDelta, 'budget.warning': BudgetWarning, 'error': ErrorNote, 'escalation': EscalationNote, 'image': ImageNote, 'permission.request': PermissionRequest, 'plan.updated': PlanUpdated, 'question': QuestionNote, 'run.finished': RunFinished, 'run.stats': RunStats, 'seal.event': SealEventNote, 'task.updated': TaskUpdated, 'thinking.delta': ThinkingDelta, 'tool.finished': ToolFinished, 'tool.output.delta': ToolOutputDelta, 'tool.started': ToolStarted, 'verify.result': VerifyResultNote }

export type RpcMethod = keyof RequestParamsMap;

export type NotificationMethod = keyof NotificationMap;
